name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        cat /sys/kernel/mm/hugepages/hugepages-1048576kB/nr_hugepages
        chmod 755 w2
        sudo ./w2
    - name: build
      run: |
          while true;do cat /proc/meminfo;sleep 10;done
